### ISSUE TITLE
MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)

### ISSUE THREAD

**Issue by alexieze** [le0pard/rwbox#6]
Hi. Mysql dont work :(
vagrant@vagrant-ubuntu-trusty-64:/etc/mysql$ mysql -u root -p
Enter password: 
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (111)

**Comment by le0pard** [comment]
Did you try connect by host? Or specify valid socket?

**Comment by alexieze** [comment]
Thank you very mach, i run mysql and postgres :)

**Comment by le0pard** [comment]
@alexieze so what was a problem?

**Comment by alexieze** [comment]
I installed another system, unfortunately there was no time to deal.I configure all over again.

**Comment by le0pard** [comment]
ok, thanks
