### ISSUE TITLE
Not sure how to use it.

### ISSUE THREAD

**Issue by joelstransky** [le0pard/rwbox#7]
Not sure I did everything right. `vagrant up` went fine. I can ssh in but the only thing in my folder is `Vagrantfile` and most of it is commented out. http://192.168.33.10/ fails. Can you clarify what to do next? DevOp's is not my strong suit.

Thanks.

Here's the contents of my resulting Vagrantfile
https://gist.github.com/joelstransky/36ac2aa4c3aeb1c45194e79b2dbeda47

**Comment by le0pard** [comment]
Next you should run `bundle install` and `rails s` inside `/vagrant` dir in box (login by `vagrant ssh`). After this http://192.168.33.10:3100/ should works

**Comment by joelstransky** [comment]
`Could not locate Gemfile or .bundle/ directory`
The directory where I ran `vagrant init leopard/rwtrusty64` from contains one and only one file, Vagrantfile.

**Comment by le0pard** [comment]
This box for ruby projects - you should use it inside this projects (look at description) :)

**Comment by joelstransky** [comment]
Oh ok, I assumed this box would at least load a basic index.html prior to the rails project being created.

**Comment by le0pard** [comment]
It can broke projects by this action, so better not to do this
