### ISSUE TITLE
mysql errors

### ISSUE THREAD

**Issue by joelstransky** [le0pard/rwbox#8]
installed rbenv, uninstalled rvm, upgraded ruby, installed bundle and rails.
Then typed `mysql -u root -p` and after typing the password `vagrant` go this error.
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)

**Comment by le0pard** [comment]
Use `localhost` hostname, skip socket

**Comment by joelstransky** [comment]
Sorry I don't know what that means.

**Comment by le0pard** [comment]
`mysql -h localhost -u root -p`

**Comment by joelstransky** [comment]
no change. same error.

**Comment by le0pard** [comment]
It shouldn't, because `-h` set not to use socket.

**Comment by joelstransky** [comment]
![image](https://cloud.githubusercontent.com/assets/200472/14700871/daef85ce-073d-11e6-98fb-cef00aa17b78.png)

**Comment by le0pard** [comment]
Check if MySQL server still working.

**Comment by joelstransky** [comment]
Thanks for the help so far. Not sure what's going on.
![image](https://cloud.githubusercontent.com/assets/200472/14701046/cc53a9e0-073e-11e6-889b-4b435ed701ba.png)

**Comment by le0pard** [comment]
```
$ mysql -h127.0.0.1 -uroot -p
Enter password:
Welcome to the MySQL monitor.  Commands end with ; or \g.
Your MySQL connection id is 2
Server version: 5.5.43-0ubuntu0.14.04.1 (Ubuntu)
```

**Comment by joelstransky** [comment]
already nuked the box after failing to reinstall mysql. I'll try that if it happens again.
