### ISSUE TITLE
Need to install MongoDB and Point to different IP address.

### ISSUE THREAD

**Issue by khanrn** [le0pard/rwbox#9]
1. I need to install `MongoDB` in that `rwbox`. How can i install and configure it to work it smoothly?
2. I've already installed `ScotchBox` virtual box at `192.168.33.10` IP address. So I need to configure this `rwbox` at `192.168.33.30` address so that I can get result on that IP address and I don't need to define the port each time. How can I do that ?

Thanks.

**Comment by le0pard** [comment]
Hello.
1. https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/
2. https://www.vagrantup.com/docs/networking/private_network.html ("STATIC IP" section)
